version: 2.1

orbs:
  clojure: hannah/clojure@dev:test

jobs:
 clojure_with_args:
    parameters:
      test_str:
        type: string
    executor:
      name: clojure/generic_exec
      wd: ~/datascript
      docker_image: circleci/clojure:lein
    steps:
      - clojure/generic_commands:
          restore_key: "dependency-cache-{{ checksum \"project.clj\" }}"
          test_str: << parameters.test_str >>
          save_key: "dependency-cache-{{ checksum \"project.clj\" }}"
          save_path: ~/.m2

workflows:
  build-test-deploy:
    jobs:
    - clojure_with_args:
        name: test_clj
        test_str: lein test-clj-all