version: 2.1

orbs:
  clojure: hannah/clojure@dev:test

# TODO: After turning this into a clojure orb, create an orb that only accepts a different run line, and use that
#  datascript:
#    jobs:
#      populated:
#        parameters:
#          test_str:
#            type: string
#        - clojure/generic-job

workflows:
  build-test-deploy:
    jobs:
    - clojure/generic_job:
        name: test_clj
        wd: ~/datascript
        docker_image: circleci/clojure:lein
        restore_key: dependency-cache-{{ checksum "project.clj" }}
        test_str: lein test-clj-all
        save_key: dependency-cache-{{ checksum "project.clj" }}
        paths:
          - ~/.m2