version: 2.1
description: hannah/clojure@dev:test orb

jobs:
  generic_job:
    parameters:
      restore_key:
        type: string
        default: "<< checksum \"project.clj\" >>"
      test_str:
        type: string
        default: "lein test"
      test_directory:
        type: string
        default: ""
      save_key:
        type: string
        default: "<< checksum \"project.clj\" >>"
      save_paths:
        type: steps
        default:
        - ~/.m2
      wd:
        type: string
      docker_image:
        type: string
    executor:
      name: generic_exec
      wd: << parameters.wd >>
      docker_image: << parameters.docker_image >>
    steps:
    - checkout
    - restore_cache:
        key: << parameters.restore_key >>
    - run: << parameters.test_str >>
    - save_cache:
        key: << parameters.save_key >>
        paths: << parameters.save_paths >>
executors:
  generic_exec:
    parameters:
      wd:
        type: string
        default: foo # ~
      docker_image:
        type: string
        default: bar # "circleci/clojure:lein"
    working_directory: << parameters.wd >>
    docker:
    - image: <<parameters.docker_image>>
