version: 2.1
description: hannah/clojure@dev:test orb

jobs:
executors:
  generic_exec:
    parameters:
      wd:
        type: string
        default: ~
      docker_image:
        type: string
        default: "circleci/clojure:lein"
    working_directory: << parameters.wd >>
    docker:
    - image: <<parameters.docker_image>>

commands:
  cached_test:
    parameters:
      restore_key:
        type: string
        default: << checksum "project.clj" >>
      pre_test_steps:
        type: steps
        default: []
      test_str:
        type: string
        default: "lein test"
      test_wd:
        type: string
        default: ""
      pre_save_steps:
        type: steps
        default: []
      save_key:
        type: string
        default: << checksum "project.clj" >>
      save_path:
        type: string
        default: ~/.m2
    steps:
      - checkout
      - restore_cache:
          key: << parameters.restore_key >>
      - steps: << parameters.pre_test_steps >>
      - when:
          condition: << parameters.test_wd >>
          steps:
          - run:
              working_directory: << parameters.test_wd >>
              command: << parameters.test_str >>
      - when:
          condition: ! << parameters.test_wd >>
          steps:
          - run: << parameters.test_str >>
      - steps: << parameters.pre_save_steps >>
      - when:
          # If you require multiple 'paths' in your
          # save_cache command, we recommend adding
          # the entire command as separate command
          # or post-step
          condition: << parameters.save_path >>
          steps:
          - save_cache:
              key: << parameters.save_key >>
              paths:
              - << parameters.save_path >>